CREATE TABLE ORDERS
(ORDER_NUM int NOT NULL AUTO_INCREMENT,
ORDER_COST DECIMAL(4,2),
PAY_METHOD Char(10),
ORDER_DATE DATE,
ORDER_DELIVERY Char(10),
PRIMARY KEY (ORDER_NUM) );

CREATE TABLE ACCOUNTS
(ACC_USER Char(25) PRIMARY KEY,
ACC_PASS Char(25)
);

INSERT INTO ACCOUNTS
VALUES
('manager', 'pass', 'manager');

INSERT INTO ACCOUNTS
VALUES
('employee', 'pass', 'employee');