SELECT ORDER_NUM as Num, ORDER_DELIVERY as OrderType, ORDER_CONTENT as pizza, ORDER_COST as Cost, PAY_METHOD as Payment, ORDER_DATE as OrderDate
FROM ORDERS;

SELECT ORDER_DELIVERY as OrderType, SUM(ORDER_COST) as totalCost
FROM ORDERS
Group by ORDER_DELIVERY;


